Refactored github actions build workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,16 +4,6 @@ on:
   push:
   workflow_dispatch:
 
-env:
-  ALL_PACKAGES: |
-    linux_rpi3
-    linux_rpi5
-    raspberrypifw
-    raspberrypiWirelessFirmware
-  ALL_INSTALLERS: |
-    rpi3-installer
-    rpi5-installer
-
 jobs:
   build_kernels:
     strategy:
@@ -22,13 +12,19 @@ jobs:
         packages: 
           - linux_rpi3
           - linux_rpi5
-    runs-on: ubuntu-24.04-arm
+    runs-on: ubuntu-latest
+    outputs:
+      linux_rpi3: ${{ steps.build.outputs.path_linux_rpi3 }}
+      linux_rpi5: ${{ steps.build.outputs.path_linux_rpi5 }}
     steps:
       - uses: actions/checkout@v4
       - uses: cachix/install-nix-action@v31
       - uses: DeterminateSystems/magic-nix-cache-action@main
       - name: Build Kernel Package
-        run: nix --accept-flake-config build .#packages.aarch64-linux.${{ matrix.packages }}
+        id : build
+        run: |
+          nix_store_path=$(nix --accept-flake-config build .#packages.aarch64-linux.${{ matrix.packages }} --print-out-paths)
+          echo "path_${{ matrix.packages }}=$nix_store_path" >> "$GITHUB_OUTPUT"
 
   build_packages:
     strategy:
@@ -37,13 +33,19 @@ jobs:
         packages:
           - raspberrypifw
           - raspberrypiWirelessFirmware
-    runs-on: ubuntu-24.04-arm
+    runs-on: ubuntu-latest
+    outputs:
+      raspberrypifw: ${{ steps.build.outputs.path_raspberrypifw }}
+      raspberrypiWirelessFirmware: ${{ steps.build.outputs.path_raspberrypiWirelessFirmware }}
     steps:
       - uses: actions/checkout@v4
       - uses: cachix/install-nix-action@v31
       - uses: DeterminateSystems/magic-nix-cache-action@main
       - name: Build Packages
-        run: nix --accept-flake-config build .#packages.aarch64-linux.${{ matrix.packages }}
+        id : build
+        run: |
+          nix_store_path=$(nix --accept-flake-config build .#packages.aarch64-linux.${{ matrix.packages }} --print-out-paths)
+          echo "path_${{ matrix.packages }}=$nix_store_path" >> "$GITHUB_OUTPUT"
 
   build_installers:
     needs: 
@@ -55,40 +57,44 @@ jobs:
         packages:
           - rpi3-installer
           - rpi5-installer
-    runs-on: ubuntu-24.04-arm
+    runs-on: ubuntu-latest
+    outputs:
+      rpi3-installer: ${{ steps.build.outputs.path_rpi3-installer }}
+      rpi5-installer: ${{ steps.build.outputs.path_rpi5-installer }}
     steps:
       - uses: actions/checkout@v4
       - uses: cachix/install-nix-action@v31
       - uses: DeterminateSystems/magic-nix-cache-action@main
       - name: Build Installers
-        run: nix --accept-flake-config build .#nixosConfigurations.${{ matrix.packages }}.config.system.build.toplevel
-
+        id : build
+        run: |
+          nix_store_path=$(nix --accept-flake-config build .#nixosConfigurations.${{ matrix.packages }}.config.system.build.toplevel --print-out-paths)
+          echo "path_${{ matrix.packages }}=$nix_store_path" >> "$GITHUB_OUTPUT"
 
   upload_artifacts:
     needs: 
       - build_kernels
       - build_packages
       - build_installers
-    runs-on: ubuntu-24.04-arm
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: cachix/install-nix-action@v31
       - uses: DeterminateSystems/magic-nix-cache-action@main
-
-      - name: Create binary cache
+      - name: Collect store paths
         run: |
-          mapfile -t packages < <(echo "$ALL_PACKAGES" | grep -v '^[[:space:]]*$')
-          mapfile -t installers < <(echo "$ALL_INSTALLERS" | grep -v '^[[:space:]]*$')
+          mkdir -p result-store/store
 
-          mkdir -p result-store
-          for pkg in "${packages[@]}"; do
-            echo "Copy ${pkg} to binary cache"
-            nix --accept-flake-config copy --no-check-sigs --to file://${PWD}/result-store .#packages.aarch64-linux.${pkg}
-          done
+          echo "#!/bin/bash" > result-store/copy-from-cache.sh
+          echo "set -euo pipefail" >> result-store/copy-from-cache.sh
+          echo "store_path=\"file://\${PWD}/\$1\"" >> result-store/copy-from-cache.sh
 
-          for pkg in "${installers[@]}"; do
-            echo "Copy ${pkg} to binary cache"
-            nix --accept-flake-config copy --no-check-sigs --to file://${PWD}/result-store .#nixosConfigurations.${pkg}.config.system.build.toplevel
+          echo '[ ${{ toJSON(needs.build_kernels.outputs) }}, ${{ toJSON(needs.build_packages.outputs) }}, ${{ toJSON(needs.build_installers.outputs) }} ]' | \
+          jq -r '.[] | to_entries[] | .value' | \
+          while read -r path; do
+            echo "Storing path: ${path}"
+            echo "nix copy --from \"\${store_path}\" \"${path}\"" >> result-store/copy-from-cache.sh
+            nix --accept-flake-config copy --no-check-sigs --to "file://${PWD}/result-store/store" "${path}"
           done
 
       - uses: actions/upload-artifact@v4
